"""Dados estáticos para uso em desenvolvimento"""
mock_restaurants = [
    {"id": 1, "name": "Bóde do Nô",
     "description": "Descrrição do restaurante",
     "classification": 4.9,
     "location": "Recife-PE",
     "url_image_logo": "url_logo",
     "url_image_banner": "url_banner"},
    {"id": 2, "name": "Imperador dos camarões",
     "description": "Descrrição do restaurante", "classification": 4.8,
     "location": "Maceió-AL", "url_image_logo": "url_logo",
     "url_image_banner": "url_banner"},
    {"id": 3, "name": "Bar da Sogra",
     "description": "Descrrição do restaurante",
     "classification": 4.1, "location": "Salvador-BA",
     "url_image_logo": "url_logo", "url_image_banner": "url_banner"},
    {"id": 4, "name": "Raspa Tácho",
     "description": "Descrrição do restaurante",
     "classification": 4.8, "location": "Fortaleza-CE",
     "url_image_logo": "url_logo", "url_image_banner": "url_banner"},
    {"id": 5, "name": "Boi na Brasa",
     "description": "Descrrição do restaurante",
     "classification": 4.9, "location": "Fortaleza-CE",
     "url_image_logo": "url_logo", "url_image_banner": "url_banner"}
]

mock_products = [
    {"id": 1, "name": "X-Bacon", "value": 20, "description": "Bacon",
     "url_image": "url_image", "restaurant_id": 1},
    {"id": 2, "name": "X-Picanha", "value": 20, "description": "Picanha",
     "url_image": "url_image", "restaurant_id": 2},
    {"id": 3, "name": "X-Salada", "value": 20, "description": "Salada",
     "url_image": "url_image", "restaurant_id": 3},
    {"id": 4, "name": "X-Frango", "value": 20, "description": "Frango",
     "url_image": "url_image", "restaurant_id": 4},
    {"id": 5, "name": "X-Batata", "value": 20, "description": "Batata",
     "url_image": "url_image", "restaurant_id": 5},
]

mock_users = [
    {"id": 1,
     "firstname": "Tony",
     "lastname": "Stark",
     "email": "ironman@icloud.com"},
    {"id": 2,
     "firstname": "Peter",
     "lastname": "Parker",
     "email": "spiderman@icloud.com"},
    {"id": 3,
     "firstname": "Bruce",
     "lastname": "Banner",
     "email": "hulk@icloud.com"},
    {"id": 4,
     "firstname": "Natasha",
     "lastname": "Romanoff",
     "email": "blackwidow@icloud.com"},
    {"id": 5,
     "firstname": "Steve",
     "lastname": "Rogers",
     "email": "captainamerica@icloud.com"}
]
