services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=staging
      - FLASK_APP=project
    volumes:
      - .:/app