"""empty message

Revision ID: c04ce36db125
Revises: 
Create Date: 2025-02-21 12:30:47.216609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04ce36db125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('client_cellphone', sa.String(length=11), nullable=False),
    sa.Column('client_cpf', sa.String(length=11), nullable=False),
    sa.Column('client_address', sa.String(length=120), nullable=False),
    sa.Column('client_address_number', sa.Integer(), nullable=False),
    sa.Column('client_address_complement', sa.String(length=120), nullable=False),
    sa.Column('client_address_neighborhood', sa.String(length=40), nullable=True),
    sa.Column('client_zip_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.Float(precision=3), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('url_image_logo', sa.String(length=800), nullable=True),
    sa.Column('url_image_banner', sa.String(length=800), nullable=True),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('has_plastic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('payment', sa.Enum('Dinheiro', 'Pix', name='payment_type'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(precision=6), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('url_image', sa.String(length=800), nullable=True),
    sa.Column('food_type', sa.Enum('Italiana', 'Japonesa', 'Árabe', 'Chinesa', 'Brasileira', 'Mexicana', 'Lanches', 'Pizza', 'Doces', name='food_type'), nullable=False),
    sa.Column('has_gluten', sa.Boolean(), nullable=False),
    sa.Column('has_lactose', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_table('products_restaurants',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_restaurants')
    op.drop_table('order_product_association')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('restaurant')
    op.drop_table('client')
    # ### end Alembic commands ###
